version: '3'
services:
  # PostgreSQL Database
  db:
    container_name: postgres
    image: postgres
    build:
      context: ./misc
    environment:
      POSTGRES_USER: adminpostgres
      POSTGRES_PASSWORD: 87654321
      POSTGRES_DB: fitness
    volumes:
      - ./misc:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  #Kafka
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "topup,input-harga"

  # Go Microservice 1
  cek-harga-service:
    build:
      context: ./microservice/cek-harga-service
    environment:
      DATABASE_URL: postgres://adminpostgres:87654321@postgres:5432/fitness
    depends_on:
      - db
    ports:
      - "8081:8081"

  # Go Microservice 2
  cek-mutasi-service:
    build:
      context: ./microservice/cek-mutasi-service
    environment:
      DATABASE_URL: postgres://adminpostgres:87654321@postgres:5432/fitness
    depends_on:
      - db
    ports:
      - "8082:8082"

  # Go Microservice 3
  cek-saldo-service:
    build:
      context: ./microservice/cek-saldo-service
    environment:
      DATABASE_URL: postgres://adminpostgres:87654321@postgres:5432/fitness
    depends_on:
      - db
    ports:
      - "8083:8083"

  # Go Microservice 4
  buyback-service:
    build:
      context: ./microservice/buyback-service
    environment:
      DATABASE_URL: postgres://adminpostgres:87654321@postgres:5432/fitness
      KAFKA_BROKERS: "kafka:9093"
    depends_on:
      - kafka
      - db
    ports:
      - "8084:8084"

  # Go Microservice 5
  topup-service:
    build:
      context: ./microservice/topup-service
    environment:
      DATABASE_URL: postgres://adminpostgres:87654321@postgres:5432/fitness
      KAFKA_BROKERS: "kafka:9093"
    depends_on:
      - kafka
      - db
    ports:
      - "8085:8085"

  # Go Microservice 6
  topup-storage-service:
    build:
      context: ./microservice/topup-storage-service
    environment:
      DATABASE_URL: postgres://adminpostgres:87654321@postgres:5432/fitness
      KAFKA_BROKERS: "kafka:9093"
    depends_on:
      - kafka
      - db
    ports:
      - "8086:8086"

  # Go Microservice 7
  buyback-storage-service:
    build:
      context: ./microservice/buyback-storage-service
    environment:
      DATABASE_URL: postgres://adminpostgres:87654321@postgres:5432/fitness
      KAFKA_BROKERS: "kafka:9093"
    depends_on:
      - kafka
      - db
    ports:
      - "8087:8087"

  # Go Microservice 8
  input-harga-service:
    build:
      context: ./microservice/input-harga-service
    environment:
      DATABASE_URL: postgres://adminpostgres:87654321@postgres:5432/fitness
      KAFKA_BROKERS: "kafka:9093"
    depends_on:
      - kafka
      - db
    ports:
      - "8088:8088"

  # Go Microservice 9
  input-harga-storage-service:
    build:
      context: ./microservice/input-harga-storage-service
    environment:
      DATABASE_URL: postgres://adminpostgres:87654321@postgres:5432/fitness
      KAFKA_BROKERS: "kafka:9093"
    depends_on:
      - kafka
      - db
    ports:
      - "8089:8089"