version: '3'
services:
  # PostgreSQL Database
  db:
    container_name: postgres
    image: postgres
    build:
      context: ./misc
    environment:
      POSTGRES_USER: adminpostgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: 87654321
    volumes:
      - ./misc:/docker-entrypoint-initdb.d
      - ./misc/pg_hba.conf:/etc/postgresql/13/main/pg_hba.conf
    ports:
      - "5431:5431"

  #Kafka
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "topup,input-harga"

  # Go Microservice 1
  cek-harga-service:
    build:
      context: ./microservice/cek-harga-service
    environment:
      DATABASE_URL: "host=db user=adminpostgres dbname=postgres password=87654321 sslmode=disable"
    depends_on:
      - db
    ports:
      - "8081:8081"
    restart: always

  # Go Microservice 2
  cek-mutasi-service:
    build:
      context: ./microservice/cek-mutasi-service
    environment:
      DATABASE_URL: "host=db user=adminpostgres dbname=postgres password=87654321 sslmode=disable"
    depends_on:
      - db
    ports:
      - "8082:8082"
    restart: always

  # Go Microservice 3
  cek-saldo-service:
    build:
      context: ./microservice/cek-saldo-service
    environment:
      DATABASE_URL: "host=db user=adminpostgres dbname=postgres password=87654321 sslmode=disable"
    depends_on:
      - db
    ports:
      - "8083:8083"
    restart: always

  # Go Microservice 4
  buyback-service:
    build:
      context: ./microservice/buyback-service
    environment:
      DATABASE_URL: "host=db user=adminpostgres dbname=postgres password=87654321 sslmode=disable"
      KAFKA_TOPIC: topup
      KAFKA_BROKERS: "kafka:9093"
    depends_on:
      - kafka
      - db
    ports:
      - "8084:8084"
    restart: always

  # Go Microservice 5
  topup-service:
    build:
      context: ./microservice/topup-service
    environment:
      DATABASE_URL: "host=db user=adminpostgres dbname=postgres password=87654321 sslmode=disable"
      KAFKA_BROKERS: "kafka:9093"
    depends_on:
      - kafka
      - db
    ports:
      - "8085:8085"
    restart: always

  # Go Microservice 6
  topup-storage-service:
    build:
      context: ./microservice/topup-storage-service
    environment:
      DATABASE_URL: "host=db user=adminpostgres dbname=postgres password=87654321 sslmode=disable"
      KAFKA_BROKERS: "kafka:9093"
      CONSUMER_GROUP: topup-group
      CONSUMER_TOPIC: topup
    depends_on:
      - kafka
      - db
    ports:
      - "8086:8086"
    restart: always

  # Go Microservice 7
  buyback-storage-service:
    build:
      context: ./microservice/buyback-storage-service
    environment:
      DATABASE_URL: "host=db user=adminpostgres dbname=postgres password=87654321 sslmode=disable"
      KAFKA_BROKERS: "kafka:9093"
      CONSUMER_GROUP: buyback-group
      CONSUMER_TOPIC: topup
    depends_on:
      - kafka
      - db
    ports:
      - "8087:8087"
    restart: always

  # Go Microservice 8
  input-harga-service:
    build:
      context: ./microservice/input-harga-service
    environment:
      DATABASE_URL: "host=db user=adminpostgres dbname=postgres password=87654321 sslmode=disable"
      KAFKA_BROKERS: "kafka:9093"
      KAFKA_TOPIC: input-harga
    depends_on:
      - kafka
      - db
    ports:
      - "8088:8088"
    restart: always

  # Go Microservice 9
  input-harga-storage-service:
    build:
      context: ./microservice/input-harga-storage-service
    environment:
      DATABASE_URL: "host=db user=adminpostgres dbname=postgres password=87654321 sslmode=disable"
      KAFKA_BROKERS: "kafka:9093"
      CONSUMER_GROUP: input-harga-group
      CONSUMER_TOPIC: input-harga
    depends_on:
      - kafka
      - db
    ports:
      - "8089:8089"
    restart: always